server:
  port: 8888
spring:
  application:
    name: configServer-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DivanioSilva/ms-config-data.git
#          username:
#          password:
      label: main

#  security:
#    user:
#      name:
#      password:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://divanio.ddns.net:8761/eureka/}
